num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))
num3 = float(input("Digite o terceiro número: "))
soma_dobro = (num1 * 2) + (num2 * 2) + (num3 * 2)
print("A soma do dobro dos três números é:", soma_dobro)
